DROP SCHEMA PUBLIC CASCADE;;

CREATE TABLE "CUSTINFO" (
	"CUST_ID" IDENTITY PRIMARY KEY,
	"CUST_NAME" VARCHAR(255) NOT NULL,
	"CUST_DOB" DATE,
	"CUST_SEX" VARCHAR(20),
	"CUST_PROJ" VARCHAR(255)
);;


CREATE TABLE "CENTER" (
	"ID" IDENTITY PRIMARY KEY,
	"CENTER_ID" VARCHAR(64) NOT NULL,
	"CENTER_PASSWORD" VARCHAR(64) NOT NULL,	
	"CENTER_NAME" VARCHAR(124) NOT NULL,
	"CENTER_DESCRIPTION" VARCHAR(2048),	
	"CENTER_LOGO" blob,
	"CENTER_OWNER_FIRSTNAME" VARCHAR(64),
	"CENTER_OWNER_MIDNAME" VARCHAR(32),	
	"CENTER_OWNER_LASTNAME" VARCHAR(64),
	"CENTER_ADDRESS1" VARCHAR(64),
    "CENTER_ADDRESS2" VARCHAR(64),
   	"CENTER_CITY" VARCHAR(64), 
   	"CENTER_STATE" VARCHAR(16), 
   	"CENTER_ZIPCODE" VARCHAR(10), 
    "CENTER_COUNTRY" VARCHAR(32),   	   	
	"CENTER_OWNER_EMAIL" VARCHAR(128),	
	"CENTER_OWNER_LANDPHONE" VARCHAR(15),	
	"CENTER_OWNER_MOBILEPHONE" VARCHAR(15),		
	"CENTER_CUSTOMER_RATING" NUMERIC,	
	"CENTER_LEVEL" NUMERIC,	
    "CENTER_CLOSE_STARTDATE" TIMESTAMP(6), 
   	"CENTER_CLOSE_ENDDATE" TIMESTAMP(6),        
    "CENTER_OPEN_STATUS" boolean	
);;
